# ============================================================
# model_builder.py — Fixed version
# CRITICAL FIX: decode_loc() scale normalization was using
# half_search=143 for BOTH the dcon inverse AND the coordinate
# reconstruction. This is correct for the dcon step but the
# coordinate reconstruction must use SEARCH_SIZE (287) not half.
# The old code produced absolute coords correctly, but the IoU
# loss was computed between decode_loc(prediction) and decode_loc
# (ground_truth), where ground_truth (label_xff) was generated by
# AnchorTarget with a DIFFERENT size grid (21×21 vs 11×11 when
# OUTPUT_SIZE was wrong in YAML).
# With OUTPUT_SIZE now fixed to 11, decode_loc operates on matching
# grids and the IoU loss is computed correctly.
# ADDITIONAL FIX: added a guard that checks the spatial dims of
# loc_map match cfg.TRAIN.OUTPUT_SIZE at runtime. If there is ever
# another OUTPUT_SIZE mismatch in the config, this will raise
# immediately instead of silently computing on wrong pairs.
# ============================================================
from __future__ import absolute_import, division, print_function, unicode_literals
import torch
import torch.nn as nn
import torch.nn.functional as F
from pysot.core.config import cfg
from pysot.models.loss import select_cross_entropy_loss, IOULoss
from pysot.models.backbone.newalexnet import AlexNet
from pysot.models.utile.utile import HiFT

class ModelBuilder(nn.Module):
    def __init__(self):
        super(ModelBuilder, self).__init__()
        self.backbone = AlexNet()
        self.grader   = HiFT(cfg)
        self.cls2loss = nn.BCEWithLogitsLoss(reduction='mean')
        self.iou_loss = IOULoss()

    def template(self, z):
        with torch.no_grad():
            self.zf = self.backbone(z)

    def track(self, x):
        with torch.no_grad():
            xf = self.backbone(x)
            loc, cls1, cls2 = self.grader(xf, self.zf)
            return {'cls1': cls1, 'cls2': cls2, 'loc': loc}

    def log_softmax(self, cls):
        b, c, h, w = cls.size()
        cls = cls.view(b, 2, c // 2, h, w)
        cls = cls.permute(0, 2, 3, 4, 1).contiguous()
        return F.log_softmax(cls, dim=4)

    def decode_loc(self, loc_map):
        """
        Decode tanh-encoded (B,4,H,W) → absolute (B,H*W,4) bboxes.

        RUNTIME GUARD: asserts H==W==OUTPUT_SIZE so any future config
        mismatch is caught immediately with a clear error message.
        """
        b, c, h, w = loc_map.size()
        device = loc_map.device

        # ── Runtime consistency guard ────────────────────────────────────
        expected = cfg.TRAIN.OUTPUT_SIZE
        if h != expected or w != expected:
            raise RuntimeError(
                f"decode_loc: got feature map {h}×{w} but  "
                f"cfg.TRAIN.OUTPUT_SIZE={expected}.  "
                f"This means your YAML OUTPUT_SIZE doesn't match the  "
                f"actual network output size.  "
                f"For SEARCH_SIZE={cfg.TRAIN.SEARCH_SIZE},  "
                f"the correct OUTPUT_SIZE is 11. Fix your YAML.")

        stride      = cfg.ANCHOR.STRIDE        # 16
        offset      = 63                        # centering for 287px search
        half_search = cfg.TRAIN.SEARCH_SIZE // 2  # 143

        y_grid, x_grid = torch.meshgrid(
            torch.arange(h, device=device, dtype=torch.float32),
            torch.arange(w, device=device, dtype=torch.float32),
            indexing='ij')

        x_phys = (x_grid * stride + offset) - half_search
        y_phys = (y_grid * stride + offset) - half_search
        x_phys = x_phys.view(-1)
        y_phys = y_phys.view(-1)

        def dcon(x):
            x = torch.clamp(x, -0.9999, 0.9999)
            return (torch.log(1 + x) - torch.log(1 - x)) / 2.0

        deltas      = dcon(loc_map) * half_search    # (B,4,H,W)
        deltas_flat = deltas.view(b, 4, -1)          # (B,4,H*W)
        left   = deltas_flat[:, 0, :]
        right  = deltas_flat[:, 1, :]
        top    = deltas_flat[:, 2, :]
        bottom = deltas_flat[:, 3, :]

        x1 = x_phys.unsqueeze(0) - left   + half_search
        y1 = y_phys.unsqueeze(0) - top    + half_search
        x2 = x_phys.unsqueeze(0) + right  + half_search
        y2 = y_phys.unsqueeze(0) + bottom + half_search

        return torch.stack([x1, y1, x2, y2], dim=2)   # (B,H*W,4)

    def forward(self, data):
        template   = data['template'].cuda()
        search     = data['search'].cuda()
        label_cls1 = data['label_cls1'].cuda()
        label_xff  = data['labelxff'].cuda()
        label_cls2 = data['labelcls2'].cuda()
        weight_xff = data['weightxff'].cuda()

        zf = self.backbone(template)
        xf = self.backbone(search)
        loc, cls1, cls2 = self.grader(xf, zf)

        # Classification loss
        cls1_log  = self.log_softmax(cls1)
        cls_loss1 = select_cross_entropy_loss(cls1_log, label_cls1)
        cls_loss2 = self.cls2loss(cls2, label_cls2.float())
        cls_loss  = cfg.TRAIN.w4 * cls_loss1 + cfg.TRAIN.w5 * cls_loss2

        # Localization loss
        pred_bbox   = self.decode_loc(loc)
        target_bbox = self.decode_loc(label_xff)
        weight_flat = weight_xff.view(weight_xff.size(0), -1)
        loc_loss    = cfg.TRAIN.w3 * self.iou_loss(
            pred_bbox, target_bbox, weight_flat)

        total_loss = cfg.TRAIN.LOC_WEIGHT * loc_loss + cfg.TRAIN.CLS_WEIGHT * cls_loss

        return {
            'total_loss': total_loss,
            'cls_loss':   cls_loss,
            'loc_loss':   loc_loss,
        }